src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[UniqueEntity('name', message: 'Ce nom est déjà pris')]
class Trick
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private $name;

    #[ORM\Column(type: 'text')]
    #[Assert\NotBlank]
    private $description;

    #[ORM\Column(type: 'datetime_immutable')]
    #[Assert\NotBlank]
    private $created_at;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $updated_at;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\ManyToOne(targetEntity: GroupTrick::class, inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: false)]
    private $group_trick;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Commentary::class, cascade: ["persist", "remove"], orphanRemoval: true)]
    private $commentaries;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Media::class, cascade: ["persist", "remove"], orphanRemoval: true)]
    private Collection $medias;

    public function __construct()
    {
        $this->commentaries = new ArrayCollection();
        $this->medias = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getGroupTrick(): ?GroupTrick
    {
        return $this->group_trick;
    }

    public function setGroupTrick(?GroupTrick $group_trick): self
    {
        $this->group_trick = $group_trick;

        return $this;
    }

    /**
     * @return Collection<int, Commentary>
     */
    public function getCommentaries(): Collection
    {
        return $this->commentaries;
    }

    public function addCommentary(Commentary $commentary): self
    {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries[] = $commentary;
            $commentary->setTrick($this);
        }

        return $this;
    }

    public function removeCommentary(Commentary $commentary): self
    {
        if ($this->commentaries->removeElement($commentary)) {
            // set the owning side to null (unless already changed)
            if ($commentary->getTrick() === $this) {
                $commentary->setTrick(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        if (str_contains(" ", $slug)) {
            $slug = str_replace(" ", "-", $slug);
        }

        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedias(): Collection
    {
        return $this->medias;
    }

    public function addMedia(Media $media): self
    {
        if (!$this->medias->contains($media)) {
            $this->medias[] = $media;
            $media->setTrick($this);
        }

        return $this;
    }

    public function removeMedia(Media $media): self
    {
        if ($this->medias->removeElement($media)) {
            // set the owning side to null (unless already changed)
            if ($media->getTrick() === $this) {
                $media->setTrick(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Commentary;
use App\Entity\Trick;
use App\Form\CommentaryType;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;

class HomeController extends AbstractController
{

    private ManagerRegistry $em;
    private PaginatorInterface $paginator;

    public function __construct(ManagerRegistry $em, PaginatorInterface $paginator)
    {
        $this->em = $em;
        $this->paginator = $paginator;
    }

    #[Route('/', name: 'app_home')]
    public function index(Request $request): Response
    {
        return $this->render('home/index.html.twig', [
            'tricks' => $this->getAllTricks($request),
        ]);
    }



    private function getAllTricks(Request $request)
    {
        $data = $this->em->getRepository(Trick::class)->findAll();
        return $this->paginator->paginate($data, $request->query->getInt("page", 1), 8);
    }
}

templates/home/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Snow Trick{% endblock %}

{% block body %}

{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Snow Trick - Accueil
{% endblock %}

{% block body %}

	<div class="baniere">
		<h1>Snow Tricks</h1>
	</div>

	<div id="allTricks" class="allTricks">
		{% for trick in tricks|sort((a, b) => a.name <=> b.name) %}
			<div class="card detailTrick bg-dark text-white" style="width: 25rem; margin:30px;">

				{% for key, media in trick.medias%}
					{% if key == 0 %}
						{% if media.fileName == null and media.type[0] == 'image' %}
							<img src="{{ media.url }}" class="card-img-top imgHome" alt="...">
						{% elseif media.fileName != null%}
							<img src="{{ asset('uploads/'~media.fileName)}}" class="card-img-top" alt="...">
						{% elseif media.type[0] == 'video' %}
							<div class="video-responsive">
								<iframe width="560" height="315" src="{{ media.url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
							</div>
						{% endif %}

					{% endif %}
				{% endfor %}

				<div class="card-body">
					<a href="{{ path('show_trick',{"slug": trick.slug}) }}" title="Voir le détail">
						<h5 class="card-title">Nom de la figure :
							{{ trick.name|upper }}</h5>
					</a>
					<h6 class="card-subtitle mb-2 text-muted">Catégorie :
						{{ trick.groupTrick.name }}</h6>

					<div class="d-flex justify-content-between">
						{% if app.user %}
							<a href="{{ path('update_trick',{"slug": trick.slug}) }}" class="btn btn-secondary">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewbox="0 0 16 16"><path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/></svg>
							</a>
							<a href="{{ path('delete_trick',{"slug": trick.slug}) }}" class="btn btn-danger">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewbox="0 0 16 16">
									<path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/></svg>
							</a>
						{% endif %}
					</div>


				</div>
			</div>
		{% endfor %}

	</div>
	<div class="pagination">
		{{ knp_pagination_render(tricks) }}
	</div>
{% endblock %}