src/Entity/Commentary.php
<?php

namespace App\Entity;

use App\Repository\CommentaryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaryRepository::class)]
class Commentary
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'commentaries')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\ManyToOne(targetEntity: Trick::class, inversedBy: 'commentaries')]
    #[ORM\JoinColumn(nullable: false)]
    private $trick;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTrick(): ?Trick
    {
        return $this->trick;
    }

    public function setTrick(?Trick $trick): self
    {
        $this->trick = $trick;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $username;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    #[
        Assert\Length(
            min: 6,
            max: 15,
            minMessage: 'Votre mot de passe doit comporter au moins {{ limit }} caractères',
            maxMessage: 'Votre mot de passe peux comporter {{ limit }} caractères maximum'
        )
    ]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Url(protocols: ['http', 'https'], message: 'Cette url : {{ value }} est invalide')]
    private $url_image;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Trick::class, orphanRemoval: true)]
    private $tricks;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: GroupTrick::class)]
    private $group_tricks;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Media::class)]
    private $media;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commentary::class)]
    private $commentaries;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    public function __construct()
    {
        $this->roles = ['ROLE_USER'];
        $this->tricks = new ArrayCollection();
        $this->group_tricks = new ArrayCollection();
        $this->media = new ArrayCollection();
        $this->commentaries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUrlImage(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(string $url_image): self
    {
        $this->url_image = $url_image;

        return $this;
    }
    /**
     * @return Collection<int, Trick>
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Trick $trick): self
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks[] = $trick;
            $trick->setUser($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): self
    {
        if ($this->tricks->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getUser() === $this) {
                $trick->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, GroupTrick>
     */
    public function getGroupTricks(): Collection
    {
        return $this->group_tricks;
    }

    public function addGroupTrick(GroupTrick $groupTrick): self
    {
        if (!$this->group_tricks->contains($groupTrick)) {
            $this->group_tricks[] = $groupTrick;
            $groupTrick->setUser($this);
        }

        return $this;
    }

    public function removeGroupTrick(GroupTrick $groupTrick): self
    {
        if ($this->group_tricks->removeElement($groupTrick)) {
            // set the owning side to null (unless already changed)
            if ($groupTrick->getUser() === $this) {
                $groupTrick->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedia(): Collection
    {
        return $this->media;
    }

    public function addMedium(Media $medium): self
    {
        if (!$this->media->contains($medium)) {
            $this->media[] = $medium;
            $medium->setUser($this);
        }

        return $this;
    }

    public function removeMedium(Media $medium): self
    {
        if ($this->media->removeElement($medium)) {
            // set the owning side to null (unless already changed)
            if ($medium->getUser() === $this) {
                $medium->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentary>
     */
    public function getCommentaries(): Collection
    {
        return $this->commentaries;
    }

    public function addCommentary(Commentary $commentary): self
    {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries[] = $commentary;
            $commentary->setUser($this);
        }

        return $this;
    }

    public function removeCommentary(Commentary $commentary): self
    {
        if ($this->commentaries->removeElement($commentary)) {
            // set the owning side to null (unless already changed)
            if ($commentary->getUser() === $this) {
                $commentary->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/CommentaryType.php
<?php

namespace App\Form;

use App\Entity\Commentary;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('content', TextareaType::class, [
            'attr' => [
                'placeholder' => 'Entrez votre message ici ...',
                'class' => 'form-control required textareaCommentary',
                'rows' => '4'
            ]
        ]);
    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commentary::class,
        ]);
    }
}

src/Controller/CommentaryController.php
<?php

namespace App\Controller;

use App\Entity\Commentary;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class CommentaryController extends AbstractController
{

    private ManagerRegistry $em;

    public function __construct(ManagerRegistry $em)
    {
        $this->em = $em;
    }


    #[Route('/delete-commentary/{id}', name: 'delete_comment')]
    #[Security("is_granted('ROLE_ADMIN') or user === commentary.getUser()", message: "Vous n'avez pas les droits suffisants")]
    public function deleteComment(int $id, Commentary $commentary): Response
    {
        $em = $this->em->getManager();
        $commentary = $this->em->getRepository(Commentary::class)->find($id);
        $this->addFlash(
            'success',
            'Commentaire supprimé !'
        );
        $em->getRepository(Commentary::class)->remove($commentary);
        $em->flush();
        return $this->redirectToRoute('show_trick', ['slug' => $commentary->getTrick()->getSlug()]);
    }
}

templates/commentary/index.html.twig
{% block body %}
	<section style="background-color: #eee;">
		<div class="container pt-4">
			<div class="row d-flex justify-content-center">
				<div class="col-md-12 col-lg-10 col-xl-8">
					<div class="card mb-3">
						<div class="card-header d-flex justify-content-between">
							<h4>Commentaires</h4>
							<a href="#commentary_content" class="btn btn-outline-primary">Ajouter un commentaire
								<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-down-circle" viewbox="0 0 16 16"><path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/></svg>
							</a>
						</div>
						{% for commentary in commentaries %}
							<div class="card-body">
								<div class="d-flex flex-start align-items-center">
									{% if commentary.user.urlImage starts with 'https' %}
										<img class="rounded-circle shadow-1-strong me-3" src="{{ commentary.user.urlImage }}" alt="avatar" width="60" height="60"/>
									{% else %}
										<img class="rounded-circle shadow-1-strong me-3" src="{{ asset('uploads/'~commentary.user.urlImage) }}" width="60" height="60">
									{% endif %}
									<div>
										<h6 class="fw-bold text-primary mb-1">{{ commentary.user.username }}</h6>
										<p class="text-muted small mb-0">
											Posté le -
											{{ commentary.createdAt|date("d/m/Y") }}
										</p>
									</div>
								</div>
								<p class="mt-3 mb-1 pb-2 contentCommentary">
									{{ commentary.content }}
								</p>
								{% if app.user %}
									{% if is_granted('ROLE_ADMIN') or app.user.username == commentary.user.username %}
										<div class="d-flex justify-content-end">
											<a href="{{ path('delete_comment',{"id": commentary.id}) }}" class="btn btn-danger">
												<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewbox="0 0 16 16">
													<path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/></svg>
											</a>
										</div>
									{% endif %}
								{% endif %}
								<hr class="my-2" style="width:98%;margin:auto"></hr>
						</div>
					{% endfor %}


					{% if app.user %}
						<form action="{{ path('show_trick', {'slug': trick.slug}) }}" method="post">
							{{ form_start(form)}}
							<div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
								<div class="d-flex flex-start w-100">
									{% if app.user.urlImage starts with 'https' %}
										<img class="rounded-circle shadow-1-strong" src="{{ app.user.urlImage }}" alt="avatar" width="60" height="60"/>
									{% else %}
										<img class="rounded-circle shadow-1-strong" src="{{ asset('uploads/'~app.user.urlImage) }}" width="60" height="60">
									{% endif %}
									<div class="form-outline w-100">
										{{ form_widget(form.content) }}
									</div>
								</div>
								<a href="#getTrick" class="btn btn-outline-primary mt-2 pt-1">Remonter la page
									<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-up-circle" viewbox="0 0 16 16">
										<path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z"/></svg>
								</a>
								<div class="float-end mt-2 pt-1">
									<button type="submit" class="btn btn-primary btn-sm">Ajouter ce commentaire</button>
									<button type="button" class="btn btn-outline-primary btn-sm">Annuler</button>
								</div>
							</div>
						</div>
						{{ form_end(form)}}
					</form>
				{% else %}
					<div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
						<div class="d-flex justify-content-between w-100">
							<div class="flash-notice d-flex w-100" id="commentary_content">
								<div class="alert alert-danger w-60 mb-0" role="alert">
									Vous devez
									<a href="{{ path('app_login') }}" class="link-secondary">vous connecter</a>
									pour ajouter un commentaire.
								</div>
								<a href="#getTrick" class="position-absolute bottom-0 end-0 mb-2 mx-2">
									<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-up-circle" viewbox="0 0 16 16">
										<path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V11.5z"/></svg>
								</a>
							</div>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="pagination mt-3">
		{{ knp_pagination_render(commentaries) }}
	</div>
</section>{% endblock %}