src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[UniqueEntity('name', message: 'Ce nom est déjà pris')]
class Trick
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private $name;

    #[ORM\Column(type: 'text')]
    #[Assert\NotBlank]
    private $description;

    #[ORM\Column(type: 'datetime_immutable')]
    #[Assert\NotBlank]
    private $created_at;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $updated_at;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\ManyToOne(targetEntity: GroupTrick::class, inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: false)]
    private $group_trick;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Commentary::class, cascade: ["persist", "remove"], orphanRemoval: true)]
    private $commentaries;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Media::class, cascade: ["persist", "remove"], orphanRemoval: true)]
    private Collection $medias;

    public function __construct()
    {
        $this->commentaries = new ArrayCollection();
        $this->medias = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getGroupTrick(): ?GroupTrick
    {
        return $this->group_trick;
    }

    public function setGroupTrick(?GroupTrick $group_trick): self
    {
        $this->group_trick = $group_trick;

        return $this;
    }

    /**
     * @return Collection<int, Commentary>
     */
    public function getCommentaries(): Collection
    {
        return $this->commentaries;
    }

    public function addCommentary(Commentary $commentary): self
    {
        if (!$this->commentaries->contains($commentary)) {
            $this->commentaries[] = $commentary;
            $commentary->setTrick($this);
        }

        return $this;
    }

    public function removeCommentary(Commentary $commentary): self
    {
        if ($this->commentaries->removeElement($commentary)) {
            // set the owning side to null (unless already changed)
            if ($commentary->getTrick() === $this) {
                $commentary->setTrick(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        if (str_contains(" ", $slug)) {
            $slug = str_replace(" ", "-", $slug);
        }

        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Media>
     */
    public function getMedias(): Collection
    {
        return $this->medias;
    }

    public function addMedia(Media $media): self
    {
        if (!$this->medias->contains($media)) {
            $this->medias[] = $media;
            $media->setTrick($this);
        }

        return $this;
    }

    public function removeMedia(Media $media): self
    {
        if ($this->medias->removeElement($media)) {
            // set the owning side to null (unless already changed)
            if ($media->getTrick() === $this) {
                $media->setTrick(null);
            }
        }

        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\GroupTrick;
use App\Entity\Trick;
use Doctrine\ORM\EntityManagerInterface;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TrickType extends AbstractType
{
    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la figure',
                'attr' => [
                    'placeholder' => 'Ex: Stalefish',
                    'class' => 'form-control required',
                ]
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'placeholder' => 'Entrez une description ...',
                    'class' => 'form-control required textareaCommentary',
                    'rows' => '4'
                ]
            ])
            ->add('groupTrick', EntityType::class, [
                'label' => 'Groupe associé à la figure',
                'class' => GroupTrick::class,
                'placeholder' => 'Choisir un groupe',
            ])
            ->add('medias', CollectionType::class, [
                'label' => false,
                'entry_type'   => MediaType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Confirmer'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

src/Controller/Security/ResetPasswordController.php
<?php

namespace App\Controller\Security;

use App\Form\ResetPasswordType;
use App\Repository\UserRepository;
use App\Service\CheckIfConnected;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Mime\Address;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class ResetPasswordController extends AbstractController
{

    public function __construct(private UserRepository $userRepository, private MailerInterface $mailer, private CheckIfConnected $checkIfConnected)
    {
    }

    #[Route('/security/reset/password', name: 'app_security_reset_password')]
    public function index(Request $request, EntityManagerInterface $em, UserPasswordHasherInterface $passwordHasher): Response
    {
        if ($this->checkIfConnected->index()) {
            $this->addFlash('danger', 'Vous êtes déjà connecté !');
            return $this->redirectToRoute('app_home');
        }

        $user = $this->userRepository->findOneBy(["email" => $request->query->get("email")]);
        $form = $this->createForm(ResetPasswordType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $newPassword = $form->getData()->getPassword();

            $hashedPassword = $passwordHasher->hashPassword($user, $newPassword);
            $user->setPassword($hashedPassword);
            $em->persist($user);
            $em->flush();
            $this->addFlash('success', 'La modification à réussi ! Vous pouvez maintenant essayer de vous connecter avec votre nouveau mot de passe.');
            return $this->redirectToRoute('app_login');
        }
        return $this->renderForm('reset_password/index.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/security/get-email', name: 'app_security_get_username')]
    public function getUsername(): Response
    {
        if ($this->checkIfConnected->index()) {
            $this->addFlash('danger', 'Vous êtes déjà connecté !');
            return $this->redirectToRoute('app_home');
        }
        return $this->render('reset_password/get_email.html.twig', []);
    }

    #[Route('/security/send-email', name: 'app_security_send_email')]
    public function verifyAndSendEmail(Request $request): RedirectResponse
    {
        if ($this->checkIfConnected->index()) {
            $this->addFlash('danger', 'Vous êtes déjà connecté !');
            return $this->redirectToRoute('app_home');
        }
        $route = 'app_security_get_username';
        if ($this->verifyEmail($request->get('_email'))) {
            $route = 'app_home';
        }
        return $this->redirectToRoute($route);
    }

    private function verifyEmail(string $email)
    {
        $user = $this->userRepository->findOneBy(["email" => $email]);
        if ($user) {
            $this->sendEmail($email);
            return true;
        }
        $this->addFlash('danger', 'Aucun compte avec cette adresse trouvé');
        return false;
    }

    private function sendEmail(string $email): void
    {
        $newEmail = (new TemplatedEmail())
            ->from(new Address('snow_trick@gmail.com', 'snowTrick'))
            ->to($email)
            ->subject('Réinitialiser le mot de passe')
            ->text('Sending emails is fun again!')
            ->htmlTemplate('reset_password/email.html.twig')
            ->context([
                'expiration_date' => new \DateTime('+1 hour', new \DateTimeZone('Europe/Paris')),
                'emailAdress' => $email,
            ]);
        $this->mailer->send($newEmail);
        $this->addFlash('success', 'Un email vous a été envoyé à l\'adresse ' . $email);
    }
}

templates/trick/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Snow Trick - detail
{% endblock %}

{% block body %}
	<div class="body" id="getTrick">
		<div class="allTricks" style="background-color: #eee;">

			<div class="card bg-dark text-white detailTrick" style="width: 70rem; margin:25px;">
				<div class="card-img-top">
					{% include('base/carrousel.html.twig') %}
				</div>
				<div class="card-body">
					<h5 class="card-title">{{ trick.name|upper }}</h5>
					<h6 class="card-subtitle mb-2 text-muted">Catégorie :
						{{ trick.groupTrick.name }}</h6>
					<p class="card-text">description :
						{{ trick.description }}</p>
					<footer class="blockquote-footer">Créé par
						{{ trick.user.username }}
						<cite title="Source Title">le
							{{ trick.createdAt|date("d/m/Y") }}</cite>
					</footer>
					<div class="d-flex justify-content-between">
						<a href="{{ path('app_home') }}" class="btn btn-outline-primary">
							<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-in-left" viewbox="0 0 16 16">
								<path fill-rule="evenodd" d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0v-2z"/>
								<path fill-rule="evenodd" d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
							</svg>
						</a>
						{% if app.user %}
							<a href="{{ path('update_trick',{"slug": trick.slug}) }}" class="btn btn-outline-secondary">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewbox="0 0 16 16"><path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/></svg>
							</a>
							<a href="{{ path('delete_trick',{"slug": trick.slug}) }}" class="btn btn-outline-danger">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewbox="0 0 16 16">
									<path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/></svg>
							</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>

	{{ include('commentary/index.html.twig') }}

{% endblock %}

templates/trick/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Snow Trick - creation
{% endblock %}

{% block body %}
	<main class="mainNewTrickForm pt-2 bg-light text-dark">
		<form enctype="multipart/form-data" class="newTrickForm m-5 bg-dark text-white" name="newTrick" method="post">
			{% include('base/trickForm.html.twig') %}
		</form>
	</main>
{% endblock %}

templates/trick/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Snow Trick - modification
{% endblock %}

{% block body %}
	<main class="mainNewTrickForm pt-2 bg-light text-dark">
		<form enctype="multipart/form-data" class="newTrickForm m-5 bg-dark text-white" name="updateTrick" method="post">
			{% include('base/trickForm.html.twig') %}
		</form>
	</main>
{% endblock %}